# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/killme.xdc

# IP: E:/HUNotes/Sophomore_Fall/5_DLD/dldProject/Basys3-Joystick-Interfacing-main/test.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_wiz_0 || ORIG_REF_NAME==xadc_wiz_0} -quiet] -quiet
